table dim_date
	lineageTag: fad18eee-b155-5535-be0e-4fc92978336a
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: ea1b0fff-c05e-5774-ac20-3cafe7178a9b
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 3268fbec-fa56-56c3-a74e-431de4d5b0a4
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: dd92ca3a-1db9-5f82-a578-750472af287f
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = User

	column month_num
		dataType: int64
		formatString: 0
		lineageTag: 37cc0ae3-263c-5480-9958-701b2e4b7ffd
		summarizeBy: none
		sourceColumn: month_num

		annotation SummarizationSetBy = User

	column month_name
		dataType: string
		lineageTag: 567b155e-7b65-5fce-a9d6-3fe4dd75d8dc
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_num

		annotation SummarizationSetBy = Automatic

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a5ee7f5e-8e27-50cb-bd2b-b1a80a15e41d
		summarizeBy: none
		sourceColumn: month_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year_month
		dataType: string
		lineageTag: ac33b5c7-342a-5581-a436-d39a93716ffd
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column week_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 56af6e09-3484-5145-ac55-c73a3e53bed4
		summarizeBy: none
		sourceColumn: week_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day_of_week_num
		dataType: int64
		formatString: 0
		lineageTag: fa1a57ef-3048-5a72-9d44-32b74a36ed93
		summarizeBy: none
		sourceColumn: day_of_week_num

		annotation SummarizationSetBy = User

	column day_name
		dataType: string
		lineageTag: 687c3c9a-bce3-55bd-8977-c7f16a314de1
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 3b990e99-ad8e-5781-b2de-d4d2cc540388
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = User

	column in_window
		dataType: int64
		formatString: #,##0
		lineageTag: aedce4d2-0cce-56a4-9451-1a172c09554e
		summarizeBy: sum
		sourceColumn: in_window

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_date.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"date", type date},
				        {"year", Int64.Type},
				        {"quarter", Int64.Type},
				        {"month_num", Int64.Type},
				        {"month_name", type text},
				        {"month_start", type date},
				        {"year_month", type text},
				        {"week_start", type date},
				        {"day_of_week_num", Int64.Type},
				        {"day_name", type text},
				        {"is_weekend", Int64.Type},
				        {"in_window", Int64.Type}
				    }, "en-US"),
				    // Column names are already clean snake_case: nothing to rename (kept as an explicit step).
				    Renamed = Table.RenameColumns(Typed, {})
				in
				    Renamed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

