table dim_product
	lineageTag: be6dae59-1a90-5e51-80bb-95351c96669a

	column product_id
		dataType: string
		isHidden
		lineageTag: 615d7281-d4bc-5554-81a8-3fd57fdc3711
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column category_en
		dataType: string
		lineageTag: 1739837d-a866-5148-a568-fe40bae983bb
		summarizeBy: none
		sourceColumn: category_en

		annotation SummarizationSetBy = Automatic

	column weight_g
		dataType: int64
		formatString: #,##0
		lineageTag: 23fd0b49-4451-5d3d-b323-e5e42cd21325
		summarizeBy: sum
		sourceColumn: weight_g

		annotation SummarizationSetBy = Automatic

	column volume_cm3
		dataType: int64
		formatString: #,##0
		lineageTag: 6343b869-f91a-5bd9-aa4f-139042dac1a1
		summarizeBy: sum
		sourceColumn: volume_cm3

		annotation SummarizationSetBy = Automatic

	column photos_qty
		dataType: int64
		formatString: #,##0
		lineageTag: 9448918b-bd7e-560c-bb01-daf421727a0d
		summarizeBy: sum
		sourceColumn: photos_qty

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_product.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"product_id", type text},
				        {"category_en", type text},
				        {"weight_g", Int64.Type},
				        {"volume_cm3", Int64.Type},
				        {"photos_qty", Int64.Type}
				    }, "en-US"),
				    // Column names are already clean snake_case: nothing to rename (kept as an explicit step).
				    Renamed = Table.RenameColumns(Typed, {})
				in
				    Renamed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

